
version: 2

models:
    - name: superstore
      description: "A dbt model for superstore database"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: superstore_aggr
      description: "A dbt model reference for superstore"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
