
version: 2

models:
    - name: superstore
      description: "A dbt model for superstore database"
      columns:
          - name: CITY
            description: "A column in the superstore table"

    - name: superstore_aggr
      description: "A dbt model reference for superstore"
      columns:
          - name: CITY
            description: "The primary key for this table"

